"""Create Prohibition_order.adoc — a separate prohibition-order letter to the
FBO manufacturer for unsafe cases.

It is generated by its own endpoint (download_prohibition_order_docx). RCM
(prepared/loose food) cases cannot have a prohibition order issued; the endpoint
returns 403 for them.

The letter repeats the first paragraph of the Prayer (Unsafe_file.adoc) so the
prohibition letter is self-contained.
"""
import sys

sys.stdout.reconfigure(encoding="utf-8")

path = "app/case_file_generator/templates/case_file_generator/Prohibition_order.adoc"

template = r"""////
// ─────────────────────────────────────────────────────────────────────────
// Prohibition Order — letter to the FBO manufacturer (ADR-001 .adoc template).
//
// This is the SECOND document for an UNSAFE sample. It is rendered by its own
// endpoint (download_prohibition_order_docx) and is addressed to the food
// business operator (manufacturer). It is NOT issued for retailer-cum-manufacturer
// (prepared/loose food) cases — the route returns 403 for those, because the
// product has no separate manufacturer and no batch/manufacturing/expiry
// details. The prayer (Unsafe_file.adoc) is still generated for RCM cases.
//
// The first document for an unsafe case is the prayer (Unsafe_file.adoc). This
// letter repeats the first paragraph of the prayer (the sample description) so
// that the prohibition letter is self-contained.
//
// Variable mapping (template var → CaseFile column / UI form field):
//   sample_code        → sample_code            / sample_code
//   sample_name        → product_name           / product_name       (aliased)
//   fso_name           → food_safety_officer_name / food_safety_officer_name (aliased)
//   packet_count       → packet_count           / packet_count
//   sample_quantity    → sample_quantity        / sample_quantity
//   per_packet_sample_quantity → computed in routes.py (sample_quantity / packet_count)
//   batch_no           → batch_no               / batch_no
//   mfg_date           → mfg_date               / mfg_date
//   expiry_date        → expiry_date            / expiry_date
//   retailer_cum_manufacturer → retailer_cum_manufacturer (bool; route rejects RCM)
//   case_number        → case_number            / case_number
//   inspection_date    → inspection_date        / inspection_date        (sampling date)
//   authorization_date → authorization_date     / authorization_date
//   manufacturer_*     → manufacturer_*         / manufacturer_*
//   retailer_*         → retailer_*             / retailer_*
//   analyst_report_no/date → analyst_report_no / analyst_report_date
//   directive_letter_no/date → directive_letter_no / directive_letter_date
//   retailer/manufacturer_report_receive_date → *_report_receive_date
// ─────────────────────────────────────────────────────────────────────────
//
"""
