# Build test_workflow_improvement.py part 1

path = r"C:/github/NSA_webservice/tests/_test_workflow_improvement.py"

parts = [
    '"""Tests for the workflow query understanding and improvement system."""',
    "",
    "import pytest",
    "",
    "from app.rag.query_understanding.workflow_query_recognizer import (",
    "    recognize_workflow_query,",
    "    extract_workflow_fields,",
    "    WorkflowRecognition,",
    "    WORKFLOW_INTENTS,",
    "    _FORM_NAME_ALIASES,",
    ")",
    "from app.rag.evaluation.workflow_evaluator import evaluate_workflow_answer",
    "from app.rag.feedback.workflow_comparator import (",
    "    compare_workflow_answers,",
    "    WorkflowAnswerComparison,",
    "    find_missing_forms,",
    "    find_extra_forms,",
    "    find_missing_steps,",
    "    find_extra_steps,",
    "    find_citation_issues,",
    "    find_factual_discrepancies,",
    "    build_improvement_summary,",
    ")",
    "from app.rag.feedback.workflow_improvement_engine import (",
    "    WorkflowImprovementEngine,",
    "    ImprovementRecommendation,",
    "    generate_training_entry,",
    "    generate_improvement_recommendations,",
    ")",
    "",
    "",
    "class TestWorkflowQueryRecognizer:",
    '    """Tests for workflow query recognition."""',
    "    ",
    "    def test_seizure_form_lookup(self):",
    '        rec = recognize_workflow_query("When a food safety officer seizes an item, which forms does he provide?")',
    "        assert rec.is_workflow_query",
    '        assert rec.intent == "seizure_form_lookup"',
    "        ",
    "    def test_sampling_process(self):",
    '        rec = recognize_workflow_query("What happens after the FSO takes a sample?")',
    "        assert rec.is_workflow_query",
    '        assert rec.intent == "sampling_process"',
    "        ",
    "    def test_form_name_alias_notice(self):",
    '        rec = recognize_workflow_query("Which form does the FSO give to the business operator as a notice?")',
    "        assert rec.is_workflow_query",
    '        assert rec.intent == "form_reference"',
    '        assert rec.form_mentioned == "v"',
    '        assert "form_name" in rec.matched_patterns',
    "        ",
    "    def test_form_name_alias_appeal(self):",
    '        rec = recognize_workflow_query("Which form can the FBO use to appeal to the designated officer?")',
    "        assert rec.is_workflow_query",
    '        assert rec.intent == "form_reference"',
    '        assert rec.form_mentioned == "viii"',
    "        ",
    "    def test_general_query(self):",
    '        rec = recognize_workflow_query("What is the FSS Act?")',
    "        assert not rec.is_workflow_query",
    '        assert rec.intent == "general"',
    "        ",
    "    def test_extract_workflow_fields(self):",
    '        fields = extract_workflow_fields("Which form does the FSO give to the business operator as a notice?")',
    '        assert fields["intent"] == "form_reference"',
    '        assert fields["form_mentioned"] == "v"',
    '        assert fields["is_workflow_query"] is True',
    "        ",
    "    def test_workflow_intents_vocab(self):",
    '        assert "seizure_form_lookup" in WORKFLOW_INTENTS',
    '        assert "sampling_process" in WORKFLOW_INTENTS',
    '        assert "form_reference" in WORKFLOW_INTENTS',
    "        ",
    "    def test_form_name_aliases(self):",
    '        assert _FORM_NAME_ALIASES["notice"] == "v"',
    '        assert _FORM_NAME_ALIASES["analyst report"] == "vii"',
    '        assert _FORM_NAME_ALIASES["appeal"] == "viii"',
    "        ",
]

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(parts))
