# Build test_workflow_improvement.py part 2b

path = r"C:/github/NSA_webservice/tests/_test_workflow_improvement.py"

parts = [
    "",
    "class TestWorkflowAnswerComparator:",
    '    """Tests for workflow answer comparison."""',
    "    ",
    "    def test_find_missing_forms(self):",
    '        sys = "Form II and Form III are used during seizure."',
    '        user = "Form II is used during seizure."',
    "        missing = find_missing_forms(sys, user)",
    '        assert "iii" in missing',
    "        ",
    "    def test_find_extra_forms(self):",
    '        sys = "Form V is used."',
    '        user = "Form V and Form VIII are used."',
    "        extra = find_extra_forms(sys, user)",
    '        assert "viii" in extra',
    "        ",
    "    def test_find_missing_steps(self):",
    '        sys = "Step 1: Submit to lab. Step 2: Lab analyzes. Step 3: Report."',
    '        user = "Step 1: Submit to lab."',
    "        missing = find_missing_steps(sys, user)",
    "        assert len(missing) >= 2",
    "        ",
    "    def test_find_extra_steps(self):",
    '        sys = "Step 1: Submit. Step 2: Analyze."',
    '        user = "Step 1: Submit. Step 2: Analyze. Step 3: Report."',
    "        extra = find_extra_steps(sys, user)",
    "        assert len(extra) >= 1",
    "        ",
    "    def test_find_citation_issues(self):",
    '        sys = ""',
    '        user = "The answer is [1] and [2]."',
    "        issues = find_citation_issues(sys, user)",
    "        assert isinstance(issues, list)",
    "        ",
    "    def test_find_factual_discrepancies(self):",
    '        sys = "Form V is for notice. Form VIII is for appeal."',
    '        user = "Form V is for notice. Form VII is for appeal."',
    "        issues = find_factual_discrepancies(sys, user)",
    "        assert len(issues) > 0",
    "        ",
    "    def test_build_improvement_summary(self):",
    '        comp = WorkflowAnswerComparison(query="test", system_answer="Form II", user_answer="Form V")',
    '        comp.missing_forms = ["viii"]',
    '        comp.extra_forms = ["v"]',
    "        summary = build_improvement_summary(comp, None)",
    '        assert "MISSING FORMS" in summary',
    '        assert "EXTRA FORMS" in summary',
    "        ",
    "    def test_comparison_has_discrepancies(self):",
    '        comp = WorkflowAnswerComparison(query="test", system_answer="Form II", user_answer="Form V")',
    '        comp.missing_forms = ["viii"]',
    "        assert comp.has_discrepancies",
    "        ",
    '        comp2 = WorkflowAnswerComparison(query="test", system_answer="Form II", user_answer="Form II")',
    "        comp2.missing_forms = []",
    "        assert not comp2.has_discrepancies",
    "        ",
    "",
    "class TestWorkflowImprovementEngine:",
    '    """Tests for workflow improvement engine."""',
    "    ",
    "    def test_generate_improvement_recommendations(self):",
    "        from app.rag.feedback.workflow_comparator import WorkflowAnswerComparison",
    "        from app.rag.evaluation.workflow_evaluator import WorkflowAnswerEvaluation, EvalScore",
    "        ",
    '        comp = WorkflowAnswerComparison(query="test", system_answer="Form II", user_answer="Form V")',
    '        comp.missing_forms = ["viii"]',
    '        comp.extra_forms = ["v"]',
    "        ",
    "        eval_res = WorkflowAnswerEvaluation(",
    '            query="test", answer="Form V", gold_answer="Form V",',
    '            faithfulness=EvalScore("faithfulness", 1.0, "", {}),',
    '            completeness=EvalScore("completeness", 1.0, "", {}),',
    '            citation_quality=EvalScore("citation_quality", 1.0, "", {}),',
    '            structure=EvalScore("structure", 1.0, "", {}),',
    '            overall=EvalScore("overall", 1.0, "", {}),',
    "        )",
    "        ",
    "        recs = generate_improvement_recommendations(comp, eval_res)",
    "        assert len(recs) > 0",
    '        assert any(r.category == "form_retrieval" for r in recs)',
    '        assert any(r.category == "hallucination" for r in recs)',
    "        ",
    "    def test_generate_training_entry(self):",
    "        from app.rag.feedback.workflow_comparator import WorkflowAnswerComparison",
    '        comp = WorkflowAnswerComparison(query="test", system_answer="Form II", user_answer="Form V")',
    '        comp.missing_forms = ["viii"]',
    '        comp.extra_forms = ["v"]',
    "        ",
    '        entries = generate_training_entry("test", "Form II", "Form V", "Form V", comp, None)',
    "        assert len(entries) >= 2",
    '        assert any(e["type"] == "answer_comparison" for e in entries)',
    '        assert any(e["type"] == "form_detection_failure" for e in entries)',
    "        ",
    "    def test_engine_analyze_query(self):",
    "        engine = WorkflowImprovementEngine()",
    "        result = engine.analyze_query(",
    '            query="Which form does the FSO give to the business operator as a notice?",',
    '            system_answer="Form V is used for notices.",',
    '            user_answer="Form V is used for notices. Form VIII is for appeals.",',
    '            gold_answer="Form V is used for notices.",',
    "        )",
    "        ",
    '        assert result.query == "Which form does the FSO give to the business operator as a notice?"',
    "        assert result.evaluation is not None",
    "        assert result.comparison is not None",
    "        assert result.recommendations is not None",
    "        assert len(result.recommendations) >= 0",
    "        assert result.training_entries is not None",
    "        ",
    "        if result.comparison.missing_forms:",
    "            assert len(result.recommendations) > 0",
    "        ",
    "        assert len(result.training_entries) >= 1",
]

with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(parts))
