"""PDF-generation tasks for the Case File Generator blueprint.

This module implements the Phase 8 PDF Assembly Engine integration.
The PDFAssemblyEngine extends the existing functionality to include:
- Annexures and evidence embedding
- Headers, footers, and page numbers via WeasyPrint @page CSS
- QR code generation for document authentication
- Signature placeholders for manual signatures
- PDF bookmarks and navigation structure
- Index pages for comprehensive case navigation
- Complete PDF assembly with professional formatting

The existing `generate_case_file_pdf` function has been enhanced to use
PDFAssemblyEngine for comprehensive PDF generation, maintaining full
backward compatibility with existing workflows.
"""

import io
import logging
import os
import zipfile
from datetime import UTC, datetime
from pathlib import Path

# Lazy import to avoid ModuleNotFoundError in deployment environments
try:
    from celery_app import celery
except ImportError:
    celery = None

logger = logging.getLogger(__name__)


# Import the Phase 8 PDFAssemblyEngine
try:
    from app.pdf_assembly import PDFAssemblyEngine
except ImportError:
    PDFAssemblyEngine = None


def generate_case_file_pdf(self, case_file_id: int, case_data: dict) -> dict:
    """Render Petition + Permission Letter PDFs from Jinja2 templates and
    save them as a ZIP archive on disk.

    This enhanced version uses the Phase 8 PDFAssemblyEngine to generate
    comprehensive PDFs including:
    - Petition and Permission Letter (existing functionality)
    - Index page for case overview
    - Annexure PDFs (if any annexures exist)
    - Evidence photo pages (if any evidence exists)
    - Professional headers, footers, and page numbers
    - QR codes for document authentication
    - Signature placeholders for official sign-offs
    - PDF bookmarks for easy navigation

    Returns a metadata dict (not the ZIP bytes):

        {
            "case_file_id": int,
            "file_path": str | None,
            "generated_at": str (ISO-8601),
            "status": "ok" | "error",
            "error": str | None,
        }

    Transient failures (file I/O) are retried; template/data failures
    are not (they will fail permanently).

    Note: no direct WeasyPrint import here — the PDFAssemblyEngine performs
    all PDF generation through the guarded ``generate_pdf_from_html`` helper,
    so this task works even on hosts without GTK/Pango (falling back to an
    error result instead of crashing at import time).
    """
    generated_at = datetime.now(UTC)

    # Use PDFAssemblyEngine if available, otherwise fallback to legacy implementation
    if PDFAssemblyEngine is not None:
        # Phase 8 implementation using PDFAssemblyEngine
        try:
            # Extract annexures from case_data (if any)
            annexures = case_data.get("annexures", [])

            # Extract photo URLs from case_data (if any evidence) — reserved for future use
            _photo_urls = case_data.get("photo_urls", [])

            # Use the Phase 8 engine to assemble complete PDF
            engine = PDFAssemblyEngine()
            pdf_bytes, error = engine.assemble_complete_case_pdf(case_file_id, case_data, annexures)

            if error:
                logger.error(
                    "Phase 8 PDF assembly failed for case_file %s: %s",
                    case_file_id,
                    error,
                )
                return _metadata(
                    case_file_id,
                    None,
                    generated_at,
                    "error",
                    f"PDF assembly failed: {error}",
                )

            if not pdf_bytes:
                logger.error(
                    "Phase 8 PDF assembly returned empty result for case_file %s",
                    case_file_id,
                )
                return _metadata(
                    case_file_id,
                    None,
                    generated_at,
                    "error",
                    "PDF assembly returned empty result",
                )

            # Create ZIP archive with the complete PDF
            zip_bytes = io.BytesIO()
            with zipfile.ZipFile(zip_bytes, "w", zipfile.ZIP_DEFLATED) as zf:
                # Add the complete PDF (combining all components)
                case_number = case_data.get("case_number", str(case_file_id)).replace("/", "_")
                zf.writestr(f"Complete_Case_{case_number}.pdf", pdf_bytes)

                # Add individual component PDFs for debugging/auditing
                # Note: These are not generated by PDFAssemblyEngine as they are
                # combined into a single PDF. If individual components are needed,
                # they should be modified in the PDFAssemblyEngine implementation.

            # Write ZIP to disk
            rel_dir = Path("pdfs") / "case_files" / generated_at.strftime("%Y/%m")
            os.makedirs(str(rel_dir), exist_ok=True)

            zip_filename = f"case_{case_file_id}_complete.pdf"
            zip_path = rel_dir / zip_filename

            with open(zip_path, "wb") as f:
                f.write(zip_bytes.getvalue())

            logger.info("Phase 8 Complete Case File ZIP saved: %s", zip_path)

            return _metadata(
                case_file_id,
                str(zip_path),
                generated_at,
                "ok",
                None,
            )

        except Exception as exc:
            logger.error(
                "Phase 8 PDF assembly exception for case_file %s: %s",
                case_file_id,
                exc,
                exc_info=True,
            )
            return _metadata(
                case_file_id,
                None,
                generated_at,
                "error",
                f"PDF assembly exception: {exc}",
            )

    else:
        # Legacy fallback implementation (Phase 1-2 only)
        logger.warning(
            "PDFAssemblyEngine not available, using legacy implementation for case_file %s",
            case_file_id,
        )
        return _legacy_generate_case_file_pdf(self, case_file_id, case_data, generated_at)


def _legacy_generate_case_file_pdf(self, case_file_id: int, case_data: dict, generated_at):
    """Legacy implementation for backward compatibility (Phase 1-2 only)."""
    from flask import render_template

    from app.utils.pdf_utils import generate_pdf_from_html, post_process_pdf_html

    # ---- Render both templates (permanent failure on error) ----
    try:
        petition_html = render_template("case_file_generator/petition.html", **case_data)
        permission_html = render_template("case_file_generator/permission_letter.html", **case_data)
        # Phase 6: cross-reference pass (list renumbering + annexure enclosures).
        petition_html = post_process_pdf_html(petition_html, case_id=case_file_id)
        permission_html = post_process_pdf_html(permission_html, case_id=case_file_id)
    except Exception as exc:
        logger.error(
            "Template render failed for case_file %s: %s",
            case_file_id,
            exc,
        )
        return _metadata(
            case_file_id,
            None,
            generated_at,
            "error",
            f"Template render failed: {exc}",
        )

    # ---- Compile PDFs (permanent failure on WeasyPrint errors) ----
    # Uses the guarded generate_pdf_from_html helper so the legacy path also
    # degrades gracefully (error result) on hosts without GTK/Pango instead
    # of raising at import time. The helper never raises; failures arrive as
    # an error tuple and short-circuit below.
    petition_pdf, petition_error = generate_pdf_from_html(petition_html)
    if petition_error:
        logger.error(
            "WeasyPrint failed for petition (case_file %s): %s",
            case_file_id,
            petition_error,
        )
        return _metadata(
            case_file_id,
            None,
            generated_at,
            "error",
            f"WeasyPrint failed: {petition_error}",
        )

    permission_pdf, permission_error = generate_pdf_from_html(permission_html)
    if permission_error:
        logger.error(
            "WeasyPrint failed for permission letter (case_file %s): %s",
            case_file_id,
            permission_error,
        )
        return _metadata(
            case_file_id,
            None,
            generated_at,
            "error",
            f"WeasyPrint failed: {permission_error}",
        )

    # ---- Write ZIP to disk (transient I/O → retry) ----
    try:
        case_number = case_data.get("case_number", str(case_file_id)).replace("/", "_")
        rel_dir = Path("pdfs") / "case_files" / generated_at.strftime("%Y/%m")
        os.makedirs(str(rel_dir), exist_ok=True)

        zip_path = rel_dir / f"case_{case_file_id}.zip"
        with zipfile.ZipFile(str(zip_path), "w", zipfile.ZIP_DEFLATED) as zf:
            zf.writestr(f"Petition_{case_number}.pdf", petition_pdf)
            zf.writestr(f"Permission_Letter_{case_number}.pdf", permission_pdf)

        logger.info("Case file ZIP saved: %s", zip_path)
    except OSError as exc:
        logger.warning("I/O error saving case file ZIP: %s", exc)
        raise self.retry(exc=exc, countdown=60) from exc
    except Exception as exc:
        logger.warning("Transient error saving case file ZIP: %s", exc)
        raise self.retry(exc=exc, countdown=60) from exc

    return _metadata(
        case_file_id,
        str(zip_path),
        generated_at,
        "ok",
        None,
    )


def _metadata(
    case_file_id: int,
    file_path: str | None,
    generated_at: datetime,
    status: str,
    error: str | None,
) -> dict[str, str | int | None]:
    return {
        "case_file_id": case_file_id,
        "file_path": file_path,
        "generated_at": generated_at.isoformat(),
        "status": status,
        "error": error,
    }


# Register as Celery task if celery is available
if celery is not None:
    generate_case_file_pdf = celery.task(bind=True, max_retries=3)(generate_case_file_pdf)
