"""add fbo_issue and fbo_issue_audit tables

Revision ID: 453157859db7
Revises: 7e5a0f6c9561
Create Date: 2026-07-16 19:00:28.463554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453157859db7'
down_revision = '7e5a0f6c9561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbo_issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fbo_id', sa.String(), nullable=False),
    sa.Column('manufacturer_fbo_id', sa.String(), nullable=True),
    sa.Column('fbo_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('fso_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.CheckConstraint("NOT (source_type = 'sample' AND state = 'dismissed')", name='ck_sample_not_dismissed'),
    sa.CheckConstraint("source_type = 'sample' OR manufacturer_fbo_id IS NULL", name='ck_sample_or_null_mfg'),
    sa.CheckConstraint("source_type IN ('inspection','sample')", name='ck_source_type'),
    sa.CheckConstraint("state IN ('open','permission_pending','permission_granted','closed','dismissed')", name='ck_state'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fbo_issue', schema=None) as batch_op:
        batch_op.create_index('idx_fbo_issue_fbo_id', ['fbo_id'], unique=False)
        batch_op.create_index('idx_fbo_issue_state', ['state'], unique=False)

    op.create_table('fbo_issue_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(), nullable=True),
    sa.Column('to_state', sa.String(), nullable=False),
    sa.Column('asserted_by', sa.String(), nullable=False),
    sa.Column('asserted_at', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['fbo_issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fbo_issue_audit', schema=None) as batch_op:
        batch_op.create_index('idx_fbo_issue_audit_issue_id', ['issue_id'], unique=False)

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicable_sections', sa.String(length=50), nullable=True))

    # Add trigger for updated_at
    op.execute("""
CREATE TRIGGER trg_fbo_issue_updated_at
AFTER UPDATE ON fbo_issue
BEGIN
    UPDATE fbo_issue SET updated_at = datetime('now') WHERE id = NEW.id;
END;
""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop trigger first
    op.execute("DROP TRIGGER trg_fbo_issue_updated_at")

    with op.batch_alter_table('case_files', schema=None) as batch_op:
        batch_op.drop_column('applicable_sections')

    with op.batch_alter_table('fbo_issue_audit', schema=None) as batch_op:
        batch_op.drop_index('idx_fbo_issue_audit_issue_id')

    op.drop_table('fbo_issue_audit')
    with op.batch_alter_table('fbo_issue', schema=None) as batch_op:
        batch_op.drop_index('idx_fbo_issue_state')
        batch_op.drop_index('idx_fbo_issue_fbo_id')

    op.drop_table('fbo_issue')
    # ### end Alembic commands ###
