"""add inspection_photos table

Revision ID: 76096260c92a
Revises: e60bc4d012c6
Create Date: 2026-07-25 07:14:55.470538

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76096260c92a"
down_revision = "e60bc4d012c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inspection_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adjudication_id", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False),
        sa.Column("caption", sa.String(length=200), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["adjudication_id"], ["adjudications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inspection_photos", schema=None) as batch_op:
        batch_op.create_index("idx_inspection_photos_adjudication_id", ["adjudication_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inspection_photos", schema=None) as batch_op:
        batch_op.drop_index("idx_inspection_photos_adjudication_id")

    op.drop_table("inspection_photos")
    # ### end Alembic commands ###
