"""add_version_id_col_to_adjudication_bill_casefile

Revision ID: a7776b1a54e3
Revises: f2203965fa39
Create Date: 2026-07-26 20:38:05.532525

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a7776b1a54e3"
down_revision = "f2203965fa39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (matches ORM default=1);
    # without it this migration fails on any non-empty table.
    with op.batch_alter_table("adjudications", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False, server_default="1"))

    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False, server_default="1"))

    with op.batch_alter_table("case_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("version_id", sa.Integer(), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("case_files", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    with op.batch_alter_table("bills", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    with op.batch_alter_table("adjudications", schema=None) as batch_op:
        batch_op.drop_column("version_id")

    # ### end Alembic commands ###
