"""add_record_audit_table

Revision ID: f2203965fa39
Revises: f8e7c4d2af5b
Create Date: 2026-07-26 20:30:36.220428

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2203965fa39"
down_revision = "f8e7c4d2af5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record_audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("record_type", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.String(length=50), nullable=False),
        sa.Column("changes", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("record_audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_record_audit_record_id"), ["record_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_record_audit_record_type"), ["record_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_record_audit_timestamp"), ["timestamp"], unique=False)
        batch_op.create_index(batch_op.f("ix_record_audit_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("record_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_record_audit_user_id"))
        batch_op.drop_index(batch_op.f("ix_record_audit_timestamp"))
        batch_op.drop_index(batch_op.f("ix_record_audit_record_type"))
        batch_op.drop_index(batch_op.f("ix_record_audit_record_id"))

    op.drop_table("record_audit")
    # ### end Alembic commands ###
