# Build workflow_comparator.py part 4

path = r"C:/github/NSA_webservice/app/rag/feedback/workflow_comparator.py"

parts = [
    "",
    "# ---------------------------------------------------------------------------",
    "# Step comparison",
    "# ---------------------------------------------------------------------------",
    "",
    "",
    "def find_missing_steps(system_answer: str, user_answer: str) -> list[str]:",
    '    """Steps present in system answer but MISSING in user answer."""',
    '    sys_steps = [m.group(2).strip() for m in _NUMBER_RE.finditer(system_answer or "")]',
    '    user_steps = [m.group(2).strip() for m in _NUMBER_RE.finditer(user_answer or "")]',
    "    missing = []",
    "    for s in sys_steps:",
    "        covered = any(s.lower() in u.lower() for u in user_steps)",
    "        if not covered:",
    "            missing.append(s)",
    "    return missing",
    "",
    "",
    "def find_extra_steps(system_answer: str, user_answer: str) -> list[str]:",
    '    """Steps present in user answer but NOT in system answer."""',
    '    sys_steps = [m.group(2).strip() for m in _NUMBER_RE.finditer(system_answer or "")]',
    '    user_steps = [m.group(2).strip() for m in _NUMBER_RE.finditer(user_answer or "")]',
    "    extra = []",
    "    for u in user_steps:",
    "        covered = any(u.lower() in s.lower() for s in sys_steps)",
    "        if not covered:",
    "            extra.append(u)",
    "    return extra",
    "",
    "",
    "def find_citation_issues(system_answer: str, user_answer: str) -> list[str]:",
    '    """Check for citation problems in user answer."""',
    "    issues = []",
    "    return issues",
    "",
    "",
    "def find_factual_discrepancies(system_answer: str, user_answer: str) -> list[str]:",
    '    """Find substantive differences between answers."""',
    "    issues = []",
    '    sys_tokens = set(re.findall(r"\\b[a-z]+\\b", system_answer or "").lower())',
    '    user_tokens = set(re.findall(r"\\b[a-z]+\\b", user_answer or "").lower())',
    '    common = set(["the", "a", "an", "is", "are", "was", "were", "to", "of", "in", "and", "or", "for", "with", "as", "on", "at", "by", "from", "this", "that", "these", "those", "it", "its", "they", "them", "their", "he", "she", "his", "her", "be", "been", "being", "have", "has", "had", "do", "does", "did", "will", "would", "could", "should", "may", "might", "must"])',
    "    sys_content = sys_tokens - common",
    "    user_content = user_tokens - common",
    "    diff = user_content - sys_content",
    "    if diff:",
    '        issues.append(f"User added unexpected terms: {", ".join(sorted(diff))[:100]}")',
    "    return issues",
    "",
    "",
    "def build_improvement_summary(comparison: WorkflowAnswerComparison) -> str:",
    '    """Build a human-readable summary of improvements needed."""',
    "    issues = []",
    "    if comparison.missing_forms:",
    '        issues.append(f"Missing forms: {", ".join(comparison.missing_forms)}")',
    "    if comparison.extra_forms:",
    '        issues.append(f"Extra forms (hallucinated): {", ".join(comparison.extra_forms)}")',
    "    if comparison.missing_steps:",
    '        issues.append(f"Missing steps: {len(comparison.missing_steps)}")',
    "    if comparison.citation_issues:",
    '        issues.append(f"Citation issues: {len(comparison.citation_issues)}")',
    "    if comparison.factual_discrepancies:",
    '        issues.append(f"Factual discrepancies: {len(comparison.factual_discrepancies)}")',
    "    if not issues:",
    '        return "No discrepancies found. Answer matches system output."',
    '    return " ".join(issues)',
]

with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(parts))
