# Build workflow_improvement_engine.py part 2

path = r"C:/github/NSA_webservice/app/rag/feedback/workflow_improvement_engine.py"

parts = [
    "",
    "@dataclass(frozen=True)",
    "class ImprovementRecommendation:",
    '    """Single improvement recommendation."""',
    "    category: str",
    '    severity: str  # "critical", "moderate", "advisory"',
    "    title: str",
    "    description: str",
    "    related_tests: list[str] = None",
    "    affected_modules: list[str] = None",
    "    ",
    "    def to_dict(self) -> dict[str, Any]:",
    "        return {",
    '            "category": self.category,',
    '            "severity": self.severity,',
    '            "title": self.title,',
    '            "description": self.description,',
    '            "related_tests": self.related_tests or [],',
    '            "affected_modules": self.affected_modules or [],',
    "        }",
    "",
    "@dataclass(frozen=True)",
    "class WorkflowImprovementResult:",
    '    """Complete improvement analysis result."""',
    "    query: str",
    "    system_answer: str",
    "    user_answer: str",
    "    gold_answer: str | None = None",
    "    evaluation: WorkflowAnswerEvaluation | None = None",
    "    comparison: WorkflowAnswerComparison | None = None",
    "    recommendations: list[ImprovementRecommendation] = None",
    "    training_entries: list[dict[str, Any]] = None",
    '    summary: str = ""',
    "    ",
    "    @property",
    "    def has_recommendations(self) -> bool:",
    "        return bool(self.recommendations)",
    "    ",
    "    def to_dict(self) -> dict[str, Any]:",
    "        return {",
    '            "query": self.query,',
    '            "evaluation": self.evaluation.to_dict() if self.evaluation else None,',
    '            "comparison": self.comparison.to_dict() if self.comparison else None,',
    '            "recommendations": [r.to_dict() for r in self.recommendations] if self.recommendations else [],',
    '            "training_entries": self.training_entries or [],',
    '            "summary": self.summary,',
    "        }",
]

with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(parts))
