# Build workflow_improvement_engine.py part 4

path = r"C:/github/NSA_webservice/app/rag/feedback/workflow_improvement_engine.py"

parts = [
    "",
    "def generate_improvement_recommendations(comparison: WorkflowAnswerComparison, evaluation: WorkflowAnswerEvaluation | None) -> list[ImprovementRecommendation]:",
    '    """Generate improvement recommendations from comparison and evaluation."""',
    "    recommendations = []",
    "    ",
    "    if comparison.missing_forms:",
    "        recommendations.append(ImprovementRecommendation(",
    '            category="form_retrieval", severity="critical",',
    '            title="Missing forms in answer: " + ", ".join(comparison.missing_forms),',
    '            description="The system answer did not include Form(s) which are present in the expected answer. The retrieval step may be missing workflow document chunks.",',
    '            related_tests=["test_document_loader", "test_ingestion_pipeline"],',
    '            affected_modules=["retrieval", "chunker", "metadata_adapter", "ingestion"],',
    "        ))",
    "    ",
    "    if comparison.extra_forms:",
    "        recommendations.append(ImprovementRecommendation(",
    '            category="hallucination", severity="critical",',
    '            title="Extraneous forms in answer: " + ", ".join(comparison.extra_forms),',
    '            description="The system answer included Form(s) which are not in the expected answer. The LLM generation step may be fabricating information.",',
    '            related_tests=["test_document_loader", "benchmark_workflow_v1.0"],',
    '            affected_modules=["generation", "prompt_template", "food_answer"],',
    "        ))",
    "    ",
    "    if comparison.missing_steps:",
    "        recommendations.append(ImprovementRecommendation(",
    '            category="step_coverage", severity="moderate",',
    '            title="Missing steps in answer: " + str(len(comparison.missing_steps)) + " step(s)",',
    '            description="The system answer omitted procedural step(s). The workflow document may not be retrieved with sufficient context.",',
    '            related_tests=["test_ingestion_pipeline"],',
    '            affected_modules=["retrieval", "generation", "prompt_template"],',
    "        ))",
    "    ",
    "    if evaluation:",
    "        if evaluation.faithfulness.score < 0.5:",
    "            recommendations.append(ImprovementRecommendation(",
    '                category="faithfulness", severity="critical",',
    '                title="Low faithfulness: " + str(round(evaluation.faithfulness.score, 2)),',
    '                description="Only of claims are supported by evidence. The retrieval system is not fetching relevant chunks.",',
    '                related_tests=["benchmark_workflow_v1.0"],',
    '                affected_modules=["retrieval", "indexer", "dense_retriever", "sparse_retriever"],',
    "            ))",
    "        if evaluation.completeness.score < 0.5:",
    "            recommendations.append(ImprovementRecommendation(",
    '                category="completeness", severity="critical",',
    '                title="Low completeness: " + str(round(evaluation.completeness.score, 2)),',
    '                description="Answer covers only partial requirements. The chunker may be splitting workflow sections too aggressively.",',
    '                related_tests=["benchmark_workflow_v1.0"],',
    '                affected_modules=["chunker", "metadata_adapter", "retrieval"],',
    "            ))",
    "    ",
    "    return recommendations",
]

with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(parts))
