# Build workflow_improvement_engine.py part 5

path = r"C:/github/NSA_webservice/app/rag/feedback/workflow_improvement_engine.py"

parts = [
    "",
    "def generate_training_entry(query: str, system_answer: str, user_answer: str, gold_answer: str | None, comparison: WorkflowAnswerComparison, evaluation: WorkflowAnswerEvaluation | None) -> list[dict[str, Any]]:",
    '    """Generate training data entries from the comparison."""',
    "    entries = []",
    "    ",
    "    entries.append({",
    '        "query": query,',
    '        "system_answer": system_answer,',
    '        "user_answer": user_answer,',
    '        "gold_answer": gold_answer,',
    '        "intent": "workflow_seizure_sampling",',
    '        "type": "answer_comparison",',
    '        "discrepancies": {',
    '            "missing_forms": comparison.missing_forms or [],',
    '            "extra_forms": comparison.extra_forms or [],',
    '            "missing_steps": comparison.missing_steps or [],',
    '            "extra_steps": comparison.extra_steps or [],',
    '            "citation_issues": comparison.citation_issues or [],',
    '            "factual_discrepancies": comparison.factual_discrepancies or [],',
    "        },",
    '        "evaluation": {',
    '            "faithfulness": evaluation.faithfulness.score if evaluation else None,',
    '            "completeness": evaluation.completeness.score if evaluation else None,',
    '            "citation_quality": evaluation.citation_quality.score if evaluation else None,',
    '            "structure": evaluation.structure.score if evaluation else None,',
    '            "overall": evaluation.overall.score if evaluation else None,',
    "        },",
    '        "created_at": "2026-10-07",',
    "    })",
    "    ",
    "    if comparison.missing_forms or comparison.extra_forms:",
    "        for form in set((comparison.missing_forms or []) + (comparison.extra_forms or [])):",
    "            entries.append({",
    '                "query": query,',
    '                "pattern": "form_" + form,',
    '                "type": "form_detection_failure",',
    '                "error": {',
    '                    "missing_forms": comparison.missing_forms or [],',
    '                    "extra_forms": comparison.extra_forms or [],',
    "                },",
    '                "lesson": "Query containing Form should retrieve workflow chunks with form definitions.",',
    '                "created_at": "2026-10-07",',
    "            })",
    "    ",
    "    if comparison.missing_steps:",
    "        entries.append({",
    '            "query": query,',
    '            "pattern": "step_coverage",',
    '            "type": "step_coverage_gap",',
    '            "error": {',
    '                "missing_steps": comparison.missing_steps,',
    "            },",
    '            "lesson": "Workflow procedure answers must include all expected steps in order.",',
    '            "created_at": "2026-10-07",',
    "        })",
    "    ",
    "    return entries",
]

with open(path, "a", encoding="utf-8") as f:
    f.write("\n".join(parts))
